version: '3'


networks:
  172.31.0.0:
    external: true

services:

  basic_php:
    restart: on-failure
    container_name: basic_php
    build:
      context: ./symfony/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    links:
      - basic_postgres
    networks:
      - 172.31.0.0


  basic_nginx:
#    restart: on-failure
    container_name: basic_nginx
    build:
      context: ./symfony/docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - basic_php
    ports:
      - 9191:9000
    networks:
      - 172.31.0.0



  basic_postgres:
    image: postgres:latest
    container_name: basic_postgres
    restart: on-failure
    ports:
      - 15432:5432
    networks:
      - 172.31.0.0
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=yakov
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test







#  lesson-mysql:
#    image: mysql:latest
#    container_name: lesson-mysql
##    command: --default-authentication-plugin=mysql_native_password
#    environment:
#     MYSQL_ROOT_PASSWORD: 1
#     MYSQL_USER: yakov
#     MYSQL_PASSWORD: 123
#     MYSQL_DATABASE: lessons
#    volumes:
#      - ./mysql:/var/lib/mysql
#    ports:
#    - 3306:3306
